name: PlatformIO CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        example: [examples/HostPing/HostPing.ino, examples/SimplePing/SimplePing.ino]

    steps:
      - uses: actions/checkout@v2.3.4
      - name: Cache pip
        uses: actions/cache@v2.1.4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Cache PlatformIO
        uses: actions/cache@v2.1.4
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio

      - name: Run PlatformIO on current branch
        run: pio ci -l "*.h" -l "*.cpp" --board=esp32doit-devkit-v1
        env:
          PLATFORMIO_CI_SRC: ${{ matrix.example }}
